name: CI
run-name: "CI run for @${{ github.actor }}, reason: {{ github.event-name }}"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          bazel version
          bazel mod graph
          bazel test -c dbg -s --test_output=all '//...'
        shell: bash

  test_mac:
    name: Test MacOS
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: |
          bazel version
          bazel mod graph
          bazel test -c dbg -s --test_output=all '//...'
        shell: bash

  clang_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 14
